### ISSUE TITLE
Burmese Unicode doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sillsdev/silkin#18]
```
What steps will reproduce the problem?
1. Burmese Unicode just appears as empty boxes
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
using 1.1 on Windows 8

Please provide any additional information below.


```

Original issue reported on code.google.com by `state...@gmail.com` on 27 Apr 2013 at 3:00

Attachments:
* [Burmese.silk](https://storage.googleapis.com/google-code-attachments/silkin/issue-18/comment-0/Burmese.silk)

**Comment by garymorris2245** [comment]
This problem was fixed with version 1.2.
